#
# Lore Command
#
language: "ua"
# мова плагіна (en - English, ua - Україна, ru - Россия)
isMaxSymbols: true
# чи ввімкнуто обмеження символів
maxSymbols: 20
# максимум символів
errorMaxSymbols: "&cТекст не повинен бути більше чим %symbols% символів"
# сповіщення якщо символів більше чим треба
errorCommandLore: "&cПомилка виповненні команди : /lore <опис>"
# сповіщення при помилці виповнення команди /lore
errorItem: "&cВи повинні тримати предмет в руці"
# сповіщення якщо в руці немає предмета
errorLvl: "&cЩоб використовувати цю команду вам треба 2 рівень"
# сповіщення якщо у гравця недостатній рівень
errorPermission: "&cУ вас немає права використовувати цю команду"
# сповіщення якщо у гравця немає права використовувати цю команду
successfullyAddedLore: "&aОпис предмету успішно доданий"
# сповіщення якщо опис предмета успішно доданий
#
# Config Reload
#
errorCommand: "&cКоманда введена неправильно"
# сповіщення при неправильному вводі команди
successfullyReloadConfig: "&cКонфіг плагина успішно перезавантажений"
# сповіщення при успішному перезавантаженні конфіга плагина
thisLanguage: "ua"
# мова поточного файлу конфігурації (не міняти для зміни мови)