#
# Lore Command
#
language: "ru"
# язык плагина (en - English, ua - Україна, ru - Россия)
isMaxSymbols: true
# Включено ли ограничение символов
maxSymbols: 20
# Максимум символов
errorMaxSymbols: "&cТекст не должен быть больше %symbols% символов"
# Сообщение если символов больше чем нужно
errorCommandLore: "&cОшибка выполнение команды : /lore <описание>"
# Сообщение при ошибке для команды /lore
errorItem: "&cВы должны держать предмет в руке"
# Сообщение если в руке нет предмета
errorLvl: "&cЧто бы использовать эту команду вам нужен 2 лвл"
# Сообщение у игрока недостаточный уровень
errorPermission: "&cУ вас нету права использовать эту команду"
# Сообщение если у игрока нет прав на команду
successfullyAddedLore: "&aОписание предмету успешно добавлено"
# Сообщение при успешном добавлении описания предметам
#
# Config Reload
#
errorCommand: "&cКоманда введена неправильно"
# Сообщение при неправильном вводе команды
successfullyReloadConfig: "&cПлагин успешно перезагружена"
# Сообщение при перезагрузке плагина
thisLanguage: "ru"
# язык текущего файла конфигурации (не изменять для изменения языка плагина)